# Generated by Django 4.2.23 on 2025-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
