# Generated by Django 4.2.23 on 2025-11-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
    ]
